#pragma once
#include <Windows.h>

enum KIT { KIT_Spacing, KIT_NewLine, KIT_Key };
struct KeyboardItem {
    KIT type;
    const char* name;
    UINT vkCode;
    float width;
};

inline KeyboardItem KeyboardLayout[] = {
    { KIT_Key, "Esc", VK_ESCAPE, 1.f },
    { KIT_Spacing, NULL, 0, .6f },
    { KIT_Key, "F1", VK_F1, 1.f },
    { KIT_Key, "F2", VK_F2, 1.f },
    { KIT_Key, "F3", VK_F3, 1.f },
    { KIT_Key, "F4", VK_F4, 1.f },
    { KIT_Spacing, NULL, 0, .6f },
    { KIT_Key, "F5", VK_F5, 1.f },
    { KIT_Key, "F6", VK_F6, 1.f },
    { KIT_Key, "F7", VK_F7, 1.f },
    { KIT_Key, "F8", VK_F8, 1.f },
    { KIT_Spacing, NULL, 0, .6f },
    { KIT_Key, "F9", VK_F9, 1.f },
    { KIT_Key, "F10", VK_F10, 1.f },
    { KIT_Key, "F11", VK_F11, 1.f },
    { KIT_Key, "F12", VK_F12, 1.f },
    { KIT_NewLine, NULL, 0, .2f },

    { KIT_Key, "~\n`", 0xC0, 1.f },
    { KIT_Key, "1\n!", 0x31, 1.f },
    { KIT_Key, "2\n@", 0x32, 1.f },
    { KIT_Key, "3\n ", 0x33, 1.f },
    { KIT_Key, "4\n$", 0x34, 1.f },
    { KIT_Key, "5\n%", 0x35, 1.f },
    { KIT_Key, "6\n^", 0x36, 1.f },
    { KIT_Key, "7\n&", 0x37, 1.f },
    { KIT_Key, "8\n*", 0x38, 1.f },
    { KIT_Key, "9\n(", 0x39, 1.f },
    { KIT_Key, "0\n)", 0x30, 1.f },
    { KIT_Key, "-\n_", 0xbd, 1.f },
    { KIT_Key, "+\n=", 0xbb, 1.f },
    { KIT_Key, "Backspace", VK_BACK, 2.f },
    { KIT_NewLine, NULL, 0, 0.f },

    { KIT_Key, "Tab", VK_TAB, 1.5f },
    { KIT_Key, "Q", 0x51, 1.f },
    { KIT_Key, "W", 0x57, 1.f },
    { KIT_Key, "E", 0x45, 1.f },
    { KIT_Key, "R", 0x52, 1.f },
    { KIT_Key, "T", 0x54, 1.f },
    { KIT_Key, "Y", 0x59, 1.f },
    { KIT_Key, "U", 0x55, 1.f },
    { KIT_Key, "I", 0x49, 1.f },
    { KIT_Key, "O", 0x4f, 1.f },
    { KIT_Key, "P", 0x50, 1.f },
    { KIT_Key, "{\n[", 0xdb, 1.f},
    { KIT_Key, "}\n]", 0xdd, 1.f },
    { KIT_Key, "|\n\\", 0xdc, 1.5f },
    { KIT_NewLine, NULL, 0, 0.f },

    { KIT_Key, "Caps Lock", VK_CAPITAL, 2.05f },
    { KIT_Key, "A", 0x41, 1.f },
    { KIT_Key, "S", 0x53, 1.f },
    { KIT_Key, "D", 0x44, 1.f },
    { KIT_Key, "F", 0x46, 1.f },
    { KIT_Key, "G", 0x47, 1.f },
    { KIT_Key, "H", 0x48, 1.f },
    { KIT_Key, "J", 0x4a, 1.f },
    { KIT_Key, "K", 0x4b, 1.f },
    { KIT_Key, "L", 0x4c, 1.f },
    { KIT_Key, ":\n;", 0xba, 1.f },
    { KIT_Key, "\"\n'", 0xde, 1.f},
    { KIT_Key, "Enter", VK_RETURN, 2.05f },
    { KIT_NewLine, NULL, 0, 0.f },

    { KIT_Key, "Shift", VK_LSHIFT, 2.3f },
    { KIT_Key, "Z", 0x5a, 1.f },
    { KIT_Key, "X", 0x58, 1.f },
    { KIT_Key, "C", 0x43, 1.f },
    { KIT_Key, "V", 0x56, 1.f },
    { KIT_Key, "B", 0x42, 1.f },
    { KIT_Key, "N", 0x4e, 1.f },
    { KIT_Key, "M", 0x4d, 1.f },
    { KIT_Key, "<\n,", 0xbc, 1.f },
    { KIT_Key, ">\n.", 0xbe, 1.f },
    { KIT_Key, "?\n/", 0xbf, 1.f },
    { KIT_Key, "Shift", VK_RSHIFT, 2.9f },
    { KIT_NewLine, NULL, 0, 0.f },

    { KIT_Key, "Ctrl", VK_LCONTROL, 1.2f },
    { KIT_Key, "Win", VK_LWIN, 1.2f },
    { KIT_Key, "Alt", VK_LMENU, 1.2f },
    { KIT_Key, "", VK_SPACE, 7.3f },
    { KIT_Key, "Alt", VK_RMENU, 1.2f },
    { KIT_Key, "Win", VK_RWIN, 1.2f },
    { KIT_Key, "Ctx", 0x5d, 1.2f },
    { KIT_Key, "Ctrl", VK_RCONTROL, 1.2f },
};
